# Usamos una imagen oficial de Python
FROM python:3.11-slim

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos el archivo de dependencias
COPY ./requirements.txt /app/requirements.txt

# Instalamos las dependencias
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# Copiamos el resto del código de la app al contenedor
COPY . /app

# Exponemos el puerto 8000 para que la API sea accesible
EXPOSE 8000